name: Roda testes e gera relatorio

on:
  push:
    branches: [main, master, exercicios/modulo-2]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checar codigo
        uses: actions/checkout@v3

      - name: Executar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Arrumar o jest
        run: chmod +x node_modules/.bin/jest

      - name: Rodar Testes
        run: npm test

      - name: Enviar relatório 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          destination_dir: .
          keep_files: true  
