name: Testes e Deploy

on:
  push:
    branches: [main, master, exercicios/modulo-2]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Executar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Permissao Jest
        run: chmod +x node_modules/.bin/jest

      - name: Rudar Tests
        run: npm test

      - name: Criar pasta de resultado
        if: always()
        run: |
          mkdir -p test-results
          echo "<h1>Relatório de Testes</h1><p>Nenhum dado disponível</p>" > test-results/index.html

      - name: Enviar ao GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-results
          keep_files: true